#ifndef FAULTY_CONSTANTS_H
#define FAULTY_CONSTANTS_H

#define MAP_DIR "./maps/"
#define TILES_DIR "./tiles/"

#define MAP_WIDTH  40
#define MAP_HEIGHT 40

#define TILE_SIZE 30

#define WINDOW_WIDTH  800
#define WINDOW_HEIGHT 600

// WINDOW_WIDTH (800) / TILE_SIZE (30) = 26
#define TILES_PER_ROW 26
// WINDOW_HEIGHT (600) / TILE_SIZE (30) = 20
#define TILES_PER_COL 20

#define TILES_PER_MAP (TILES_PER_ROW * TILES_PER_COL)

#endif
